// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_tests.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_http_5ftests_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_http_5ftests_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_http_5ftests_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_http_5ftests_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_http_5ftests_2eproto;
namespace mesos {
namespace test {
class ParentMessage;
struct ParentMessageDefaultTypeInternal;
extern ParentMessageDefaultTypeInternal _ParentMessage_default_instance_;
class TestSlaveMessage;
struct TestSlaveMessageDefaultTypeInternal;
extern TestSlaveMessageDefaultTypeInternal _TestSlaveMessage_default_instance_;
class TestSlaveMessage_SomeSlaveMapEntry_DoNotUse;
struct TestSlaveMessage_SomeSlaveMapEntry_DoNotUseDefaultTypeInternal;
extern TestSlaveMessage_SomeSlaveMapEntry_DoNotUseDefaultTypeInternal _TestSlaveMessage_SomeSlaveMapEntry_DoNotUse_default_instance_;
}  // namespace test
}  // namespace mesos
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mesos {
namespace test {
enum TestSlaveMessage_E : int {
  TestSlaveMessage_E_A_SLAVE_ENUM = 0,
};

bool TestSlaveMessage_E_IsValid(int value);
constexpr TestSlaveMessage_E TestSlaveMessage_E_E_MIN = static_cast<TestSlaveMessage_E>(0);
constexpr TestSlaveMessage_E TestSlaveMessage_E_E_MAX = static_cast<TestSlaveMessage_E>(0);
constexpr int TestSlaveMessage_E_E_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor*
TestSlaveMessage_E_descriptor();
template <typename T>
const std::string& TestSlaveMessage_E_Name(T value) {
  static_assert(std::is_same<T, TestSlaveMessage_E>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to E_Name().");
  return TestSlaveMessage_E_Name(static_cast<TestSlaveMessage_E>(value));
}
template <>
inline const std::string& TestSlaveMessage_E_Name(TestSlaveMessage_E value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TestSlaveMessage_E_descriptor,
                                                 0, 0>(
      static_cast<int>(value));
}
inline bool TestSlaveMessage_E_Parse(absl::string_view name, TestSlaveMessage_E* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TestSlaveMessage_E>(
      TestSlaveMessage_E_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class TestSlaveMessage_SomeSlaveMapEntry_DoNotUse final : public ::google::protobuf::internal::MapEntry<TestSlaveMessage_SomeSlaveMapEntry_DoNotUse,
    bool, bool,
    ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
    ::google::protobuf::internal::WireFormatLite::TYPE_BOOL> {
public:
  typedef ::google::protobuf::internal::MapEntry<TestSlaveMessage_SomeSlaveMapEntry_DoNotUse, 
    bool, bool,
    ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
    ::google::protobuf::internal::WireFormatLite::TYPE_BOOL> SuperType;
  TestSlaveMessage_SomeSlaveMapEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestSlaveMessage_SomeSlaveMapEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit TestSlaveMessage_SomeSlaveMapEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const TestSlaveMessage_SomeSlaveMapEntry_DoNotUse& other);
  static const TestSlaveMessage_SomeSlaveMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TestSlaveMessage_SomeSlaveMapEntry_DoNotUse*>(&_TestSlaveMessage_SomeSlaveMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::google::protobuf::Message::MergeFrom;
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_http_5ftests_2eproto;
};
// -------------------------------------------------------------------

class TestSlaveMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.test.TestSlaveMessage) */ {
 public:
  inline TestSlaveMessage() : TestSlaveMessage(nullptr) {}
  ~TestSlaveMessage() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR TestSlaveMessage(::google::protobuf::internal::ConstantInitialized);

  TestSlaveMessage(const TestSlaveMessage& from);
  TestSlaveMessage(TestSlaveMessage&& from) noexcept
    : TestSlaveMessage() {
    *this = ::std::move(from);
  }

  inline TestSlaveMessage& operator=(const TestSlaveMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestSlaveMessage& operator=(TestSlaveMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestSlaveMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestSlaveMessage* internal_default_instance() {
    return reinterpret_cast<const TestSlaveMessage*>(
               &_TestSlaveMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TestSlaveMessage& a, TestSlaveMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(TestSlaveMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestSlaveMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestSlaveMessage* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestSlaveMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestSlaveMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const TestSlaveMessage& from) {
    TestSlaveMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestSlaveMessage* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "mesos.test.TestSlaveMessage";
  }
  protected:
  explicit TestSlaveMessage(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  using E = TestSlaveMessage_E;
  static constexpr E A_SLAVE_ENUM = TestSlaveMessage_E_A_SLAVE_ENUM;
  static inline bool E_IsValid(int value) {
    return TestSlaveMessage_E_IsValid(value);
  }
  static constexpr E E_MIN = TestSlaveMessage_E_E_MIN;
  static constexpr E E_MAX = TestSlaveMessage_E_E_MAX;
  static constexpr int E_ARRAYSIZE = TestSlaveMessage_E_E_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* E_descriptor() {
    return TestSlaveMessage_E_descriptor();
  }
  template <typename T>
  static inline const std::string& E_Name(T value) {
    return TestSlaveMessage_E_Name(value);
  }
  static inline bool E_Parse(absl::string_view name, E* value) {
    return TestSlaveMessage_E_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSomeSlaveFieldsFieldNumber = 2,
    kSomeSlaveMapFieldNumber = 3,
    kSomeSlaveEnumsFieldNumber = 5,
    kSomeSlaveFieldFieldNumber = 1,
    kSomeSlaveEnumFieldNumber = 4,
  };
  // repeated bool some_slave_fields = 2;
  int some_slave_fields_size() const;
  private:
  int _internal_some_slave_fields_size() const;

  public:
  void clear_some_slave_fields() ;
  bool some_slave_fields(int index) const;
  void set_some_slave_fields(int index, bool value);
  void add_some_slave_fields(bool value);
  const ::google::protobuf::RepeatedField<bool>& some_slave_fields() const;
  ::google::protobuf::RepeatedField<bool>* mutable_some_slave_fields();

  private:
  const ::google::protobuf::RepeatedField<bool>& _internal_some_slave_fields() const;
  ::google::protobuf::RepeatedField<bool>* _internal_mutable_some_slave_fields();

  public:
  // map<bool, bool> some_slave_map = 3;
  int some_slave_map_size() const;
  private:
  int _internal_some_slave_map_size() const;

  public:
  void clear_some_slave_map() ;
  const ::google::protobuf::Map<bool, bool>& some_slave_map() const;
  ::google::protobuf::Map<bool, bool>* mutable_some_slave_map();

  private:
  const ::google::protobuf::Map<bool, bool>& _internal_some_slave_map() const;
  ::google::protobuf::Map<bool, bool>* _internal_mutable_some_slave_map();

  public:
  // repeated .mesos.test.TestSlaveMessage.E some_slave_enums = 5;
  int some_slave_enums_size() const;
  private:
  int _internal_some_slave_enums_size() const;

  public:
  void clear_some_slave_enums() ;
  public:
  ::mesos::test::TestSlaveMessage_E some_slave_enums(int index) const;
  void set_some_slave_enums(int index, ::mesos::test::TestSlaveMessage_E value);
  void add_some_slave_enums(::mesos::test::TestSlaveMessage_E value);
  const ::google::protobuf::RepeatedField<int>& some_slave_enums() const;
  ::google::protobuf::RepeatedField<int>* mutable_some_slave_enums();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_some_slave_enums() const;
  ::google::protobuf::RepeatedField<int>* _internal_mutable_some_slave_enums();

  public:
  // optional bool some_slave_field = 1;
  bool has_some_slave_field() const;
  void clear_some_slave_field() ;
  bool some_slave_field() const;
  void set_some_slave_field(bool value);

  private:
  bool _internal_some_slave_field() const;
  void _internal_set_some_slave_field(bool value);

  public:
  // optional .mesos.test.TestSlaveMessage.E some_slave_enum = 4;
  bool has_some_slave_enum() const;
  void clear_some_slave_enum() ;
  ::mesos::test::TestSlaveMessage_E some_slave_enum() const;
  void set_some_slave_enum(::mesos::test::TestSlaveMessage_E value);

  private:
  ::mesos::test::TestSlaveMessage_E _internal_some_slave_enum() const;
  void _internal_set_some_slave_enum(::mesos::test::TestSlaveMessage_E value);

  public:
  // @@protoc_insertion_point(class_scope:mesos.test.TestSlaveMessage)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5, 3, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<bool> some_slave_fields_;
    ::google::protobuf::internal::MapField<TestSlaveMessage_SomeSlaveMapEntry_DoNotUse, bool, bool,
                      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
                      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>
        some_slave_map_;
    ::google::protobuf::RepeatedField<int> some_slave_enums_;
    bool some_slave_field_;
    int some_slave_enum_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_5ftests_2eproto;
};// -------------------------------------------------------------------

class ParentMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.test.ParentMessage) */ {
 public:
  inline ParentMessage() : ParentMessage(nullptr) {}
  ~ParentMessage() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ParentMessage(::google::protobuf::internal::ConstantInitialized);

  ParentMessage(const ParentMessage& from);
  ParentMessage(ParentMessage&& from) noexcept
    : ParentMessage() {
    *this = ::std::move(from);
  }

  inline ParentMessage& operator=(const ParentMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParentMessage& operator=(ParentMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParentMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ParentMessage* internal_default_instance() {
    return reinterpret_cast<const ParentMessage*>(
               &_ParentMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ParentMessage& a, ParentMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ParentMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParentMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParentMessage* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ParentMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ParentMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ParentMessage& from) {
    ParentMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParentMessage* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "mesos.test.ParentMessage";
  }
  protected:
  explicit ParentMessage(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSomeSlaveMessagesFieldNumber = 2,
    kSomeSlaveMessageFieldNumber = 1,
  };
  // repeated .mesos.test.TestSlaveMessage some_slave_messages = 2;
  int some_slave_messages_size() const;
  private:
  int _internal_some_slave_messages_size() const;

  public:
  void clear_some_slave_messages() ;
  ::mesos::test::TestSlaveMessage* mutable_some_slave_messages(int index);
  ::google::protobuf::RepeatedPtrField< ::mesos::test::TestSlaveMessage >*
      mutable_some_slave_messages();
  private:
  const ::google::protobuf::RepeatedPtrField<::mesos::test::TestSlaveMessage>& _internal_some_slave_messages() const;
  ::google::protobuf::RepeatedPtrField<::mesos::test::TestSlaveMessage>* _internal_mutable_some_slave_messages();
  public:
  const ::mesos::test::TestSlaveMessage& some_slave_messages(int index) const;
  ::mesos::test::TestSlaveMessage* add_some_slave_messages();
  const ::google::protobuf::RepeatedPtrField< ::mesos::test::TestSlaveMessage >&
      some_slave_messages() const;
  // optional .mesos.test.TestSlaveMessage some_slave_message = 1;
  bool has_some_slave_message() const;
  void clear_some_slave_message() ;
  const ::mesos::test::TestSlaveMessage& some_slave_message() const;
  PROTOBUF_NODISCARD ::mesos::test::TestSlaveMessage* release_some_slave_message();
  ::mesos::test::TestSlaveMessage* mutable_some_slave_message();
  void set_allocated_some_slave_message(::mesos::test::TestSlaveMessage* value);
  void unsafe_arena_set_allocated_some_slave_message(::mesos::test::TestSlaveMessage* value);
  ::mesos::test::TestSlaveMessage* unsafe_arena_release_some_slave_message();

  private:
  const ::mesos::test::TestSlaveMessage& _internal_some_slave_message() const;
  ::mesos::test::TestSlaveMessage* _internal_mutable_some_slave_message();

  public:
  // @@protoc_insertion_point(class_scope:mesos.test.ParentMessage)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 2, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::mesos::test::TestSlaveMessage > some_slave_messages_;
    ::mesos::test::TestSlaveMessage* some_slave_message_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_5ftests_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TestSlaveMessage

// optional bool some_slave_field = 1;
inline bool TestSlaveMessage::has_some_slave_field() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void TestSlaveMessage::clear_some_slave_field() {
  _impl_.some_slave_field_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool TestSlaveMessage::some_slave_field() const {
  // @@protoc_insertion_point(field_get:mesos.test.TestSlaveMessage.some_slave_field)
  return _internal_some_slave_field();
}
inline void TestSlaveMessage::set_some_slave_field(bool value) {
  _internal_set_some_slave_field(value);
  // @@protoc_insertion_point(field_set:mesos.test.TestSlaveMessage.some_slave_field)
}
inline bool TestSlaveMessage::_internal_some_slave_field() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.some_slave_field_;
}
inline void TestSlaveMessage::_internal_set_some_slave_field(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.some_slave_field_ = value;
}

// repeated bool some_slave_fields = 2;
inline int TestSlaveMessage::_internal_some_slave_fields_size() const {
  return _internal_some_slave_fields().size();
}
inline int TestSlaveMessage::some_slave_fields_size() const {
  return _internal_some_slave_fields_size();
}
inline void TestSlaveMessage::clear_some_slave_fields() {
  _internal_mutable_some_slave_fields()->Clear();
}
inline bool TestSlaveMessage::some_slave_fields(int index) const {
  // @@protoc_insertion_point(field_get:mesos.test.TestSlaveMessage.some_slave_fields)
  return _internal_some_slave_fields().Get(index);
}
inline void TestSlaveMessage::set_some_slave_fields(int index, bool value) {
  _internal_mutable_some_slave_fields()->Set(index, value);
  // @@protoc_insertion_point(field_set:mesos.test.TestSlaveMessage.some_slave_fields)
}
inline void TestSlaveMessage::add_some_slave_fields(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_some_slave_fields()->Add(value);
  // @@protoc_insertion_point(field_add:mesos.test.TestSlaveMessage.some_slave_fields)
}
inline const ::google::protobuf::RepeatedField<bool>& TestSlaveMessage::some_slave_fields() const {
  // @@protoc_insertion_point(field_list:mesos.test.TestSlaveMessage.some_slave_fields)
  return _internal_some_slave_fields();
}
inline ::google::protobuf::RepeatedField<bool>* TestSlaveMessage::mutable_some_slave_fields() {
  // @@protoc_insertion_point(field_mutable_list:mesos.test.TestSlaveMessage.some_slave_fields)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_some_slave_fields();
}

inline const ::google::protobuf::RepeatedField<bool>& TestSlaveMessage::_internal_some_slave_fields() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.some_slave_fields_;
}
inline ::google::protobuf::RepeatedField<bool>* TestSlaveMessage::_internal_mutable_some_slave_fields() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.some_slave_fields_;
}

// map<bool, bool> some_slave_map = 3;
inline int TestSlaveMessage::_internal_some_slave_map_size() const {
  return _internal_some_slave_map().size();
}
inline int TestSlaveMessage::some_slave_map_size() const {
  return _internal_some_slave_map_size();
}
inline void TestSlaveMessage::clear_some_slave_map() {
  _impl_.some_slave_map_.Clear();
}
inline const ::google::protobuf::Map<bool, bool>& TestSlaveMessage::_internal_some_slave_map() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.some_slave_map_.GetMap();
}
inline const ::google::protobuf::Map<bool, bool>& TestSlaveMessage::some_slave_map() const {
  // @@protoc_insertion_point(field_map:mesos.test.TestSlaveMessage.some_slave_map)
  return _internal_some_slave_map();
}
inline ::google::protobuf::Map<bool, bool>* TestSlaveMessage::_internal_mutable_some_slave_map() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.some_slave_map_.MutableMap();
}
inline ::google::protobuf::Map<bool, bool>* TestSlaveMessage::mutable_some_slave_map() {
  // @@protoc_insertion_point(field_mutable_map:mesos.test.TestSlaveMessage.some_slave_map)
  return _internal_mutable_some_slave_map();
}

// optional .mesos.test.TestSlaveMessage.E some_slave_enum = 4;
inline bool TestSlaveMessage::has_some_slave_enum() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void TestSlaveMessage::clear_some_slave_enum() {
  _impl_.some_slave_enum_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::mesos::test::TestSlaveMessage_E TestSlaveMessage::some_slave_enum() const {
  // @@protoc_insertion_point(field_get:mesos.test.TestSlaveMessage.some_slave_enum)
  return _internal_some_slave_enum();
}
inline void TestSlaveMessage::set_some_slave_enum(::mesos::test::TestSlaveMessage_E value) {
  _internal_set_some_slave_enum(value);
  // @@protoc_insertion_point(field_set:mesos.test.TestSlaveMessage.some_slave_enum)
}
inline ::mesos::test::TestSlaveMessage_E TestSlaveMessage::_internal_some_slave_enum() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::mesos::test::TestSlaveMessage_E>(_impl_.some_slave_enum_);
}
inline void TestSlaveMessage::_internal_set_some_slave_enum(::mesos::test::TestSlaveMessage_E value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  assert(::mesos::test::TestSlaveMessage_E_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.some_slave_enum_ = value;
}

// repeated .mesos.test.TestSlaveMessage.E some_slave_enums = 5;
inline int TestSlaveMessage::_internal_some_slave_enums_size() const {
  return _internal_some_slave_enums().size();
}
inline int TestSlaveMessage::some_slave_enums_size() const {
  return _internal_some_slave_enums_size();
}
inline void TestSlaveMessage::clear_some_slave_enums() {
  _internal_mutable_some_slave_enums()->Clear();
}
inline ::mesos::test::TestSlaveMessage_E TestSlaveMessage::some_slave_enums(int index) const {
  // @@protoc_insertion_point(field_get:mesos.test.TestSlaveMessage.some_slave_enums)
  return static_cast<::mesos::test::TestSlaveMessage_E>(_internal_some_slave_enums().Get(index));
}
inline void TestSlaveMessage::set_some_slave_enums(int index, ::mesos::test::TestSlaveMessage_E value) {
  assert(::mesos::test::TestSlaveMessage_E_IsValid(value));
  _internal_mutable_some_slave_enums()->Set(index, value);
  // @@protoc_insertion_point(field_set:mesos.test.TestSlaveMessage.some_slave_enums)
}
inline void TestSlaveMessage::add_some_slave_enums(::mesos::test::TestSlaveMessage_E value) {
  assert(::mesos::test::TestSlaveMessage_E_IsValid(value));
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_some_slave_enums()->Add(value);
  // @@protoc_insertion_point(field_add:mesos.test.TestSlaveMessage.some_slave_enums)
}
inline const ::google::protobuf::RepeatedField<int>& TestSlaveMessage::some_slave_enums() const {
  // @@protoc_insertion_point(field_list:mesos.test.TestSlaveMessage.some_slave_enums)
  return _internal_some_slave_enums();
}
inline ::google::protobuf::RepeatedField<int>* TestSlaveMessage::mutable_some_slave_enums() {
  // @@protoc_insertion_point(field_mutable_list:mesos.test.TestSlaveMessage.some_slave_enums)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_some_slave_enums();
}
inline const ::google::protobuf::RepeatedField<int>& TestSlaveMessage::_internal_some_slave_enums() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.some_slave_enums_;
}
inline ::google::protobuf::RepeatedField<int>* TestSlaveMessage::_internal_mutable_some_slave_enums() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.some_slave_enums_;
}

// -------------------------------------------------------------------

// ParentMessage

// optional .mesos.test.TestSlaveMessage some_slave_message = 1;
inline bool ParentMessage::has_some_slave_message() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.some_slave_message_ != nullptr);
  return value;
}
inline void ParentMessage::clear_some_slave_message() {
  if (_impl_.some_slave_message_ != nullptr) _impl_.some_slave_message_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::mesos::test::TestSlaveMessage& ParentMessage::_internal_some_slave_message() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::mesos::test::TestSlaveMessage* p = _impl_.some_slave_message_;
  return p != nullptr ? *p : reinterpret_cast<const ::mesos::test::TestSlaveMessage&>(::mesos::test::_TestSlaveMessage_default_instance_);
}
inline const ::mesos::test::TestSlaveMessage& ParentMessage::some_slave_message() const {
  // @@protoc_insertion_point(field_get:mesos.test.ParentMessage.some_slave_message)
  return _internal_some_slave_message();
}
inline void ParentMessage::unsafe_arena_set_allocated_some_slave_message(::mesos::test::TestSlaveMessage* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.some_slave_message_);
  }
  _impl_.some_slave_message_ = reinterpret_cast<::mesos::test::TestSlaveMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mesos.test.ParentMessage.some_slave_message)
}
inline ::mesos::test::TestSlaveMessage* ParentMessage::release_some_slave_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mesos::test::TestSlaveMessage* released = _impl_.some_slave_message_;
  _impl_.some_slave_message_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::mesos::test::TestSlaveMessage* ParentMessage::unsafe_arena_release_some_slave_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:mesos.test.ParentMessage.some_slave_message)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mesos::test::TestSlaveMessage* temp = _impl_.some_slave_message_;
  _impl_.some_slave_message_ = nullptr;
  return temp;
}
inline ::mesos::test::TestSlaveMessage* ParentMessage::_internal_mutable_some_slave_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.some_slave_message_ == nullptr) {
    auto* p = CreateMaybeMessage<::mesos::test::TestSlaveMessage>(GetArenaForAllocation());
    _impl_.some_slave_message_ = reinterpret_cast<::mesos::test::TestSlaveMessage*>(p);
  }
  return _impl_.some_slave_message_;
}
inline ::mesos::test::TestSlaveMessage* ParentMessage::mutable_some_slave_message() {
  ::mesos::test::TestSlaveMessage* _msg = _internal_mutable_some_slave_message();
  // @@protoc_insertion_point(field_mutable:mesos.test.ParentMessage.some_slave_message)
  return _msg;
}
inline void ParentMessage::set_allocated_some_slave_message(::mesos::test::TestSlaveMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::mesos::test::TestSlaveMessage*>(_impl_.some_slave_message_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::mesos::test::TestSlaveMessage*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.some_slave_message_ = reinterpret_cast<::mesos::test::TestSlaveMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:mesos.test.ParentMessage.some_slave_message)
}

// repeated .mesos.test.TestSlaveMessage some_slave_messages = 2;
inline int ParentMessage::_internal_some_slave_messages_size() const {
  return _internal_some_slave_messages().size();
}
inline int ParentMessage::some_slave_messages_size() const {
  return _internal_some_slave_messages_size();
}
inline void ParentMessage::clear_some_slave_messages() {
  _internal_mutable_some_slave_messages()->Clear();
}
inline ::mesos::test::TestSlaveMessage* ParentMessage::mutable_some_slave_messages(int index) {
  // @@protoc_insertion_point(field_mutable:mesos.test.ParentMessage.some_slave_messages)
  return _internal_mutable_some_slave_messages()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::mesos::test::TestSlaveMessage >*
ParentMessage::mutable_some_slave_messages() {
  // @@protoc_insertion_point(field_mutable_list:mesos.test.ParentMessage.some_slave_messages)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_some_slave_messages();
}
inline const ::mesos::test::TestSlaveMessage& ParentMessage::some_slave_messages(int index) const {
  // @@protoc_insertion_point(field_get:mesos.test.ParentMessage.some_slave_messages)
    return _internal_some_slave_messages().Get(index);
}
inline ::mesos::test::TestSlaveMessage* ParentMessage::add_some_slave_messages() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::mesos::test::TestSlaveMessage* _add = _internal_mutable_some_slave_messages()->Add();
  // @@protoc_insertion_point(field_add:mesos.test.ParentMessage.some_slave_messages)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::mesos::test::TestSlaveMessage >&
ParentMessage::some_slave_messages() const {
  // @@protoc_insertion_point(field_list:mesos.test.ParentMessage.some_slave_messages)
  return _internal_some_slave_messages();
}
inline const ::google::protobuf::RepeatedPtrField<::mesos::test::TestSlaveMessage>&
ParentMessage::_internal_some_slave_messages() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.some_slave_messages_;
}
inline ::google::protobuf::RepeatedPtrField<::mesos::test::TestSlaveMessage>*
ParentMessage::_internal_mutable_some_slave_messages() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.some_slave_messages_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace test
}  // namespace mesos


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mesos::test::TestSlaveMessage_E> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::mesos::test::TestSlaveMessage_E>() {
  return ::mesos::test::TestSlaveMessage_E_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_http_5ftests_2eproto_2epb_2eh
