// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_tests.proto

#include "http_tests.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mesos {
namespace test {
      template <typename>
PROTOBUF_CONSTEXPR TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct TestSlaveMessage_SomeSlaveMapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestSlaveMessage_SomeSlaveMapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestSlaveMessage_SomeSlaveMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TestSlaveMessage_SomeSlaveMapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestSlaveMessage_SomeSlaveMapEntry_DoNotUseDefaultTypeInternal _TestSlaveMessage_SomeSlaveMapEntry_DoNotUse_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR TestSlaveMessage::TestSlaveMessage(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.some_slave_fields_)*/ {},
      /* decltype(_impl_.some_slave_map_) */ {},
      /*decltype(_impl_.some_slave_enums_)*/ {},
      /*decltype(_impl_.some_slave_field_)*/ false,
      /*decltype(_impl_.some_slave_enum_)*/ 0,
    } {}
struct TestSlaveMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestSlaveMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestSlaveMessageDefaultTypeInternal() {}
  union {
    TestSlaveMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestSlaveMessageDefaultTypeInternal _TestSlaveMessage_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR ParentMessage::ParentMessage(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.some_slave_messages_)*/ {},
      /*decltype(_impl_.some_slave_message_)*/ nullptr,
    } {}
struct ParentMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParentMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParentMessageDefaultTypeInternal() {}
  union {
    ParentMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParentMessageDefaultTypeInternal _ParentMessage_default_instance_;
}  // namespace test
}  // namespace mesos
static ::_pb::Metadata file_level_metadata_http_5ftests_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_http_5ftests_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_http_5ftests_2eproto = nullptr;
const ::uint32_t TableStruct_http_5ftests_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse, value_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _impl_.some_slave_field_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _impl_.some_slave_fields_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _impl_.some_slave_map_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _impl_.some_slave_enum_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::TestSlaveMessage, _impl_.some_slave_enums_),
    0,
    ~0u,
    ~0u,
    1,
    ~0u,
    PROTOBUF_FIELD_OFFSET(::mesos::test::ParentMessage, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::ParentMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::mesos::test::ParentMessage, _impl_.some_slave_message_),
    PROTOBUF_FIELD_OFFSET(::mesos::test::ParentMessage, _impl_.some_slave_messages_),
    0,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::mesos::test::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse)},
        {12, 25, -1, sizeof(::mesos::test::TestSlaveMessage)},
        {30, 40, -1, sizeof(::mesos::test::ParentMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::mesos::test::_TestSlaveMessage_SomeSlaveMapEntry_DoNotUse_default_instance_._instance,
    &::mesos::test::_TestSlaveMessage_default_instance_._instance,
    &::mesos::test::_ParentMessage_default_instance_._instance,
};
const char descriptor_table_protodef_http_5ftests_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\020http_tests.proto\022\nmesos.test\"\316\002\n\020TestS"
    "laveMessage\022\030\n\020some_slave_field\030\001 \001(\010\022\031\n"
    "\021some_slave_fields\030\002 \003(\010\022F\n\016some_slave_m"
    "ap\030\003 \003(\0132..mesos.test.TestSlaveMessage.S"
    "omeSlaveMapEntry\0227\n\017some_slave_enum\030\004 \001("
    "\0162\036.mesos.test.TestSlaveMessage.E\0228\n\020som"
    "e_slave_enums\030\005 \003(\0162\036.mesos.test.TestSla"
    "veMessage.E\0323\n\021SomeSlaveMapEntry\022\013\n\003key\030"
    "\001 \001(\010\022\r\n\005value\030\002 \001(\010:\0028\001\"\025\n\001E\022\020\n\014A_SLAVE"
    "_ENUM\020\000\"\204\001\n\rParentMessage\0228\n\022some_slave_"
    "message\030\001 \001(\0132\034.mesos.test.TestSlaveMess"
    "age\0229\n\023some_slave_messages\030\002 \003(\0132\034.mesos"
    ".test.TestSlaveMessage"
};
static ::absl::once_flag descriptor_table_http_5ftests_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_http_5ftests_2eproto = {
    false,
    false,
    502,
    descriptor_table_protodef_http_5ftests_2eproto,
    "http_tests.proto",
    &descriptor_table_http_5ftests_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_http_5ftests_2eproto::offsets,
    file_level_metadata_http_5ftests_2eproto,
    file_level_enum_descriptors_http_5ftests_2eproto,
    file_level_service_descriptors_http_5ftests_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_http_5ftests_2eproto_getter() {
  return &descriptor_table_http_5ftests_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_http_5ftests_2eproto(&descriptor_table_http_5ftests_2eproto);
namespace mesos {
namespace test {
const ::google::protobuf::EnumDescriptor* TestSlaveMessage_E_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_http_5ftests_2eproto);
  return file_level_enum_descriptors_http_5ftests_2eproto[0];
}
bool TestSlaveMessage_E_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr TestSlaveMessage_E TestSlaveMessage::A_SLAVE_ENUM;
constexpr TestSlaveMessage_E TestSlaveMessage::E_MIN;
constexpr TestSlaveMessage_E TestSlaveMessage::E_MAX;
constexpr int TestSlaveMessage::E_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse() {}
TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::TestSlaveMessage_SomeSlaveMapEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
void TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::MergeFrom(const TestSlaveMessage_SomeSlaveMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5ftests_2eproto_getter, &descriptor_table_http_5ftests_2eproto_once,
      file_level_metadata_http_5ftests_2eproto[0]);
}
// ===================================================================

class TestSlaveMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<TestSlaveMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_._has_bits_);
  static void set_has_some_slave_field(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_some_slave_enum(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

TestSlaveMessage::TestSlaveMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mesos.test.TestSlaveMessage)
}
TestSlaveMessage::TestSlaveMessage(const TestSlaveMessage& from) : ::google::protobuf::Message() {
  TestSlaveMessage* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.some_slave_fields_){from._impl_.some_slave_fields_},
      /* decltype(_impl_.some_slave_map_) */ {},
      decltype(_impl_.some_slave_enums_){from._internal_some_slave_enums()},
      decltype(_impl_.some_slave_field_){},
      decltype(_impl_.some_slave_enum_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _this->_impl_.some_slave_map_.MergeFrom(from._impl_.some_slave_map_);
  ::memcpy(&_impl_.some_slave_field_, &from._impl_.some_slave_field_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.some_slave_enum_) -
    reinterpret_cast<char*>(&_impl_.some_slave_field_)) + sizeof(_impl_.some_slave_enum_));

  // @@protoc_insertion_point(copy_constructor:mesos.test.TestSlaveMessage)
}
inline void TestSlaveMessage::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.some_slave_fields_){arena},
      /* decltype(_impl_.some_slave_map_) */ {::google::protobuf::internal::ArenaInitialized(), arena},
      decltype(_impl_.some_slave_enums_){arena},
      decltype(_impl_.some_slave_field_){false},
      decltype(_impl_.some_slave_enum_){0},
  };
}
TestSlaveMessage::~TestSlaveMessage() {
  // @@protoc_insertion_point(destructor:mesos.test.TestSlaveMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TestSlaveMessage::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.some_slave_fields_.~RepeatedField();
  _impl_.some_slave_map_.~MapField();
  _internal_mutable_some_slave_enums()->~RepeatedField();
}
void TestSlaveMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void TestSlaveMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:mesos.test.TestSlaveMessage)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_some_slave_fields()->Clear();
  _impl_.some_slave_map_.Clear();
  _internal_mutable_some_slave_enums()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.some_slave_field_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.some_slave_enum_) -
        reinterpret_cast<char*>(&_impl_.some_slave_field_)) + sizeof(_impl_.some_slave_enum_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TestSlaveMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 3, 0, 2> TestSlaveMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_TestSlaveMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bool some_slave_field = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TestSlaveMessage, _impl_.some_slave_field_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_field_)}},
    // repeated bool some_slave_fields = 2;
    {::_pbi::TcParser::FastV8R1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_fields_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional .mesos.test.TestSlaveMessage.E some_slave_enum = 4;
    {::_pbi::TcParser::FastEr0S1,
     {32, 1, 0, PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_enum_)}},
    // repeated .mesos.test.TestSlaveMessage.E some_slave_enums = 5;
    {::_pbi::TcParser::FastEr0R1,
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_enums_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool some_slave_field = 1;
    {PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_field_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // repeated bool some_slave_fields = 2;
    {PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_fields_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kBool)},
    // map<bool, bool> some_slave_map = 3;
    {PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_map_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // optional .mesos.test.TestSlaveMessage.E some_slave_enum = 4;
    {PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_enum_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // repeated .mesos.test.TestSlaveMessage.E some_slave_enums = 5;
    {PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_enums_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kEnumRange)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<decltype(TestSlaveMessage()._impl_.some_slave_map_)>(0, 1, 0)},
    {0, 1},
    {0, 1},
  }}, {{
  }},
};

::uint8_t* TestSlaveMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mesos.test.TestSlaveMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional bool some_slave_field = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_some_slave_field(), target);
  }

  // repeated bool some_slave_fields = 2;
  for (int i = 0, n = this->_internal_some_slave_fields_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_some_slave_fields().Get(i), target);
  }

  // map<bool, bool> some_slave_map = 3;
  if (!_internal_some_slave_map().empty()) {
    using MapType = ::google::protobuf::Map<bool, bool>;
    using WireHelper = TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::Funcs;
    const auto& field = _internal_some_slave_map();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            3, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            3, entry.first, entry.second, target, stream);
      }
    }
  }

  // optional .mesos.test.TestSlaveMessage.E some_slave_enum = 4;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        4, this->_internal_some_slave_enum(), target);
  }

  // repeated .mesos.test.TestSlaveMessage.E some_slave_enums = 5;
  for (int i = 0, n = this->_internal_some_slave_enums_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, static_cast<::mesos::test::TestSlaveMessage_E>(this->_internal_some_slave_enums().Get(i)),
        target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mesos.test.TestSlaveMessage)
  return target;
}

::size_t TestSlaveMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mesos.test.TestSlaveMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bool some_slave_fields = 2;
  {
    std::size_t data_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_some_slave_fields_size())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_some_slave_fields_size());
    ;
    total_size += tag_size + data_size;
  }
  // map<bool, bool> some_slave_map = 3;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_some_slave_map_size());
  for (const auto& entry : _internal_some_slave_map()) {
    total_size += TestSlaveMessage_SomeSlaveMapEntry_DoNotUse::Funcs::ByteSizeLong(entry.first, entry.second);
  }
  // repeated .mesos.test.TestSlaveMessage.E some_slave_enums = 5;
  {
    std::size_t data_size = 0;
    auto count = static_cast<std::size_t>(this->_internal_some_slave_enums_size());

    for (std::size_t i = 0; i < count; ++i) {
      data_size += ::_pbi::WireFormatLite::EnumSize(
          this->_internal_some_slave_enums().Get(static_cast<int>(i)));
    }
    total_size += data_size;
    total_size += std::size_t{1} * count;
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional bool some_slave_field = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2;
    }

    // optional .mesos.test.TestSlaveMessage.E some_slave_enum = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_some_slave_enum());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TestSlaveMessage::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    TestSlaveMessage::MergeImpl
};
const ::google::protobuf::Message::ClassData*TestSlaveMessage::GetClassData() const { return &_class_data_; }


void TestSlaveMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TestSlaveMessage*>(&to_msg);
  auto& from = static_cast<const TestSlaveMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mesos.test.TestSlaveMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_some_slave_fields()->MergeFrom(from._internal_some_slave_fields());
  _this->_impl_.some_slave_map_.MergeFrom(from._impl_.some_slave_map_);
  _this->_internal_mutable_some_slave_enums()->MergeFrom(from._internal_some_slave_enums());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.some_slave_field_ = from._impl_.some_slave_field_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.some_slave_enum_ = from._impl_.some_slave_enum_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestSlaveMessage::CopyFrom(const TestSlaveMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mesos.test.TestSlaveMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TestSlaveMessage::IsInitialized() const {
  return true;
}

void TestSlaveMessage::InternalSwap(TestSlaveMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.some_slave_fields_.InternalSwap(&other->_impl_.some_slave_fields_);
  _impl_.some_slave_map_.InternalSwap(&other->_impl_.some_slave_map_);
  _impl_.some_slave_enums_.InternalSwap(&other->_impl_.some_slave_enums_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_enum_)
      + sizeof(TestSlaveMessage::_impl_.some_slave_enum_)
      - PROTOBUF_FIELD_OFFSET(TestSlaveMessage, _impl_.some_slave_field_)>(
          reinterpret_cast<char*>(&_impl_.some_slave_field_),
          reinterpret_cast<char*>(&other->_impl_.some_slave_field_));
}

::google::protobuf::Metadata TestSlaveMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5ftests_2eproto_getter, &descriptor_table_http_5ftests_2eproto_once,
      file_level_metadata_http_5ftests_2eproto[1]);
}
// ===================================================================

class ParentMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<ParentMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ParentMessage, _impl_._has_bits_);
  static const ::mesos::test::TestSlaveMessage& some_slave_message(const ParentMessage* msg);
  static void set_has_some_slave_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::mesos::test::TestSlaveMessage& ParentMessage::_Internal::some_slave_message(const ParentMessage* msg) {
  return *msg->_impl_.some_slave_message_;
}
ParentMessage::ParentMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mesos.test.ParentMessage)
}
ParentMessage::ParentMessage(const ParentMessage& from) : ::google::protobuf::Message() {
  ParentMessage* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.some_slave_messages_){from._impl_.some_slave_messages_},
      decltype(_impl_.some_slave_message_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.some_slave_message_ = new ::mesos::test::TestSlaveMessage(*from._impl_.some_slave_message_);
  }

  // @@protoc_insertion_point(copy_constructor:mesos.test.ParentMessage)
}
inline void ParentMessage::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.some_slave_messages_){arena},
      decltype(_impl_.some_slave_message_){nullptr},
  };
}
ParentMessage::~ParentMessage() {
  // @@protoc_insertion_point(destructor:mesos.test.ParentMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ParentMessage::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.some_slave_messages_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.some_slave_message_;
}
void ParentMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void ParentMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:mesos.test.ParentMessage)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_some_slave_messages()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.some_slave_message_ != nullptr);
    _impl_.some_slave_message_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ParentMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ParentMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ParentMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ParentMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .mesos.test.TestSlaveMessage some_slave_messages = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(ParentMessage, _impl_.some_slave_messages_)}},
    // optional .mesos.test.TestSlaveMessage some_slave_message = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ParentMessage, _impl_.some_slave_message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .mesos.test.TestSlaveMessage some_slave_message = 1;
    {PROTOBUF_FIELD_OFFSET(ParentMessage, _impl_.some_slave_message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .mesos.test.TestSlaveMessage some_slave_messages = 2;
    {PROTOBUF_FIELD_OFFSET(ParentMessage, _impl_.some_slave_messages_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::mesos::test::TestSlaveMessage>()},
    {::_pbi::TcParser::GetTable<::mesos::test::TestSlaveMessage>()},
  }}, {{
  }},
};

::uint8_t* ParentMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mesos.test.ParentMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .mesos.test.TestSlaveMessage some_slave_message = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::some_slave_message(this),
        _Internal::some_slave_message(this).GetCachedSize(), target, stream);
  }

  // repeated .mesos.test.TestSlaveMessage some_slave_messages = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_some_slave_messages_size()); i < n; i++) {
    const auto& repfield = this->_internal_some_slave_messages().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mesos.test.ParentMessage)
  return target;
}

::size_t ParentMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mesos.test.ParentMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .mesos.test.TestSlaveMessage some_slave_messages = 2;
  total_size += 1UL * this->_internal_some_slave_messages_size();
  for (const auto& msg : this->_internal_some_slave_messages()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // optional .mesos.test.TestSlaveMessage some_slave_message = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.some_slave_message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ParentMessage::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    ParentMessage::MergeImpl
};
const ::google::protobuf::Message::ClassData*ParentMessage::GetClassData() const { return &_class_data_; }


void ParentMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ParentMessage*>(&to_msg);
  auto& from = static_cast<const ParentMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mesos.test.ParentMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_some_slave_messages()->MergeFrom(from._internal_some_slave_messages());
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_some_slave_message()->::mesos::test::TestSlaveMessage::MergeFrom(
        from._internal_some_slave_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ParentMessage::CopyFrom(const ParentMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mesos.test.ParentMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ParentMessage::IsInitialized() const {
  return true;
}

void ParentMessage::InternalSwap(ParentMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.some_slave_messages_.InternalSwap(&other->_impl_.some_slave_messages_);
  swap(_impl_.some_slave_message_, other->_impl_.some_slave_message_);
}

::google::protobuf::Metadata ParentMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5ftests_2eproto_getter, &descriptor_table_http_5ftests_2eproto_once,
      file_level_metadata_http_5ftests_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace test
}  // namespace mesos
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
